- name: Cria VMs em lote no OpenShift Virtualization
  hosts: localhost
  vars:
    numero_de_vms: 3
    namespace: algumas-vms-para-estressar
    vm_password: abacaxi
  tasks:
  - name: Cria Namespace para Teste
    kubernetes.core.k8s:
     name: "{{ namespace }}"
     api_version: v1
     kind: Namespace
     state: present

  - name: Gerar matriz de nomes de VMs
    set_fact:
      vm_name: "{{ vm_name | default([]) + ['vm-teste-' ~ item] }}"
      mac_address: "{{ mac_address | default([]) + ['52:54:00' | community.general.random_mac] }}"
    with_sequence: start=0 end={{ numero_de_vms - 1}}

  - name: Cria vms de acordo com o numero  
    kubernetes.core.k8s:
     state: absent
     template: 'vm-template.yaml.j2'
    with_sequence: start=0 end={{ numero_de_vms -1 }}
