- name: Stress CPU using stress
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Run CPU stress test
      ansible.builtin.command:
        cmd: "stress --cpu 4 --timeout 30s"
      poll: 0
      async: 3600
